In [1]:
import numpy as np 
import pandas as pd 


In [20]:
X = np.array([[5,10,1],[7,3,1],[100,5,1]])

(3, 3)


array([[  5,  10,   1],
       [  7,   3,   1],
       [100,   5,   1]])

In [21]:
Y = np.array([[1,0,0],[0,1,0],[0,0,1]])

(3, 3)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
w_1 = np.array([[0.2,0.4,1],[0.15,0.75,1],[0.3,0.01,1]])

(3, 3)


array([[0.2 , 0.4 , 1.  ],
       [0.15, 0.75, 1.  ],
       [0.3 , 0.01, 1.  ]])

In [44]:
w_2 = np.array([[0.9,0.25,0.12],[0.99,0.01,0.5]])

(3, 3)


array([[0.9 , 0.25, 0.12],
       [0.99, 0.01, 0.5 ],
       [1.  , 1.  , 1.  ]])

In [24]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [25]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [47]:
for back in range(10):
    
    in_o = np.dot(X, w_1)

    out_o = sigmoid(in_o)

    error = out_o - Y

    x = error.sum()
    print(x)

    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    deriv = derror_douto * douto_dino

    deriv_final = np.dot(X.T, deriv)

    w_1 -= deriv_final



-6.583096979035147e-05
-6.58522982395734e-05
-6.587360402651968e-05
-6.589488717918693e-05
-6.591614772475486e-05
-6.593738569147202e-05
-6.595860110621432e-05
-6.597979399681648e-05
-6.600096439073871e-05
-6.602211231540139e-05
-6.604323779840607e-05
-6.606434086698081e-05
-6.608542154875688e-05
-6.610647987077037e-05
-6.612751586046086e-05
-6.614852954556043e-05
-6.616952095265009e-05
-6.619049010915992e-05
-6.621143704258896e-05
-6.623236178017549e-05
-6.625326434878307e-05
-6.62741447754578e-05
-6.629500308798296e-05
-6.631583931254598e-05
-6.633665347696081e-05
-6.635744560755753e-05
-6.637821573218019e-05
-6.639896387730025e-05
-6.641969006946074e-05
-6.644039433605274e-05
-6.646107670387188e-05
-6.64817371998965e-05
-6.650237585084194e-05
-6.652299268316241e-05
-6.654358772438296e-05
-6.656416100032206e-05
-6.658471253853605e-05
-6.660524236509776e-05
-6.662575050670624e-05
-6.66462369903548e-05
-6.666670184255174e-05
-6.668714508932282e-05
-6.670756675765271e-05
-6.672796687393

/tmp/ipykernel_58727/4033946986.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))
